name: Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
              uses: actions/checkout@v2

          - name: Install dependencies and build app
            run: npm install && npm run build

          - name: Create env file
            run: echo "${{ vars.ENV_FILE }}" > .env

          - name: Deploy
              run: |
                git config --global user.email "aleksicnikola46@gmail.com"
                git config --global user.name "NikolaAleksic1996"
                git checkout --orphan gh-pages
                git --work-tree dist add --all
                git --work-tree dist commit -m "Deploy"
                git push origin HEAD:gh-pages --force
              env:
                NODE_ENV: production